# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: messages.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


class PieceType(betterproto.Enum):
    PAWN = 0
    QUEEN = 1


@dataclass
class Coordinates(betterproto.Message):
    col: str = betterproto.string_field(1)
    row: int = betterproto.int32_field(2)


@dataclass
class Piece(betterproto.Message):
    coordinates: "Coordinates" = betterproto.message_field(1)
    color: str = betterproto.string_field(2)
    type: "PieceType" = betterproto.enum_field(3)


@dataclass
class Square(betterproto.Message):
    col: str = betterproto.string_field(1)
    row: int = betterproto.int32_field(2)
    movable: bool = betterproto.bool_field(3)
    content: "Piece" = betterproto.message_field(4)


@dataclass
class Row(betterproto.Message):
    squares: List["Square"] = betterproto.message_field(1)


@dataclass
class Board(betterproto.Message):
    rows: List["Row"] = betterproto.message_field(1)
