name: kortex
channels:
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
      - file:kortex_api-2.3.0.post34-py3-none-any.whl
      - rria-api==1.0.13
      - keyboard
      - Flask
      - waitress
      - opencv-python
      - numpy
      - torch
      - torchvision
      - torchaudio
      - ultralytics==8.2.68
      - "betterproto[compiler]"